### ISSUE TITLE
Neovim support

### ISSUE THREAD

**Issue by 0xd3e** [bfrg/vim-fzy-find#1]
Hi,

I came across your plugin and it looks quite promising.
I found out quickly that it doesn't work with Neovim and have also seen in the project description that it is intended to only work with Vim.

However, I'd like to ask if you have any plan to support Neovim. I'm not that experienced with Vimscript, but I'd be happy to help.

**Comment by bfrg** [comment]
Sorry but I have no intention to add Neovim support, simply because I don't use it myself. I want to keep my plugins as simple as possible. Supporting two separate editors is also a lot of work.

Have you tried any of the [other plugins](https://github.com/search?q=vim+fzy), maybe vim-picker? They all seem to support both editors.

**Comment by 0xd3e** [comment]
Thanks for your answer. Thats totally understandable. In fact I found vim-picker an hour after I opened this issue and installed it today. It works well, so I'm closing this issue.
